[package]
name = "play-ground"
version = "0.1.0"
authors = ["jiayuxin <13520723393@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.0"